// Mocks generated by Mockito 5.4.4 from annotations
// in kinetix_mobile/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kinetix_mobile/data/datasources/remote_data_source.dart' as _i3;
import 'package:kinetix_mobile/domain/entities/workout.dart' as _i2;
import 'package:kinetix_mobile/domain/repositories/workout_repository.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWorkout_0 extends _i1.SmartFake implements _i2.Workout {
  _FakeWorkout_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataSource extends _i1.Mock implements _i3.RemoteDataSource {
  MockRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<Map<String, dynamic>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> register(
    String? email,
    String? password,
    String? name,
    String? role,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            email,
            password,
            name,
            role,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getTodayWorkout() => (super.noSuchMethod(
        Invocation.method(
          #getTodayWorkout,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<dynamic> getWeekWorkouts(String? date) => (super.noSuchMethod(
        Invocation.method(
          #getWeekWorkouts,
          [date],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getWorkoutHistory() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkoutHistory,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<dynamic> getAllWorkoutLogs() => (super.noSuchMethod(
        Invocation.method(
          #getAllWorkoutLogs,
          [],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<Map<String, dynamic>> logWorkout(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #logWorkout,
          [data],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> updateWorkoutLog(
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWorkoutLog,
          [
            id,
            data,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getCurrentPlan() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentPlan,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> createCheckIn(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCheckIn,
          [data],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getCheckIns() => (super.noSuchMethod(
        Invocation.method(
          #getCheckIns,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> deleteCheckIn(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCheckIn,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getPendingCheckIns() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingCheckIns,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>> verifyCheckIn(
    String? id,
    String? status,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyCheckIn,
          [
            id,
            status,
            reason,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> syncBatch(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncBatch,
          [data],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getSyncChanges(String? since) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSyncChanges,
          [since],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getUploadSignature() => (super.noSuchMethod(
        Invocation.method(
          #getUploadSignature,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getGamificationStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #getGamificationStatus,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getBalance() => (super.noSuchMethod(
        Invocation.method(
          #getBalance,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> clearBalance() => (super.noSuchMethod(
        Invocation.method(
          #clearBalance,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> createWeighIn({
    required double? weight,
    DateTime? date,
    String? photoUrl,
    String? notes,
    String? planId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createWeighIn,
          [],
          {
            #weight: weight,
            #date: date,
            #photoUrl: photoUrl,
            #notes: notes,
            #planId: planId,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getWeighInHistory() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeighInHistory,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>?> getLatestWeighIn() => (super.noSuchMethod(
        Invocation.method(
          #getLatestWeighIn,
          [],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<Map<String, dynamic>> getTrainerClients() => (super.noSuchMethod(
        Invocation.method(
          #getTrainerClients,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAllUsers() => (super.noSuchMethod(
        Invocation.method(
          #getAllUsers,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>> createUser({
    required String? email,
    required String? password,
    required String? firstName,
    required String? lastName,
    required String? role,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [],
          {
            #email: email,
            #password: password,
            #firstName: firstName,
            #lastName: lastName,
            #role: role,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getAdminStats() => (super.noSuchMethod(
        Invocation.method(
          #getAdminStats,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> assignClientToTrainer({
    required String? clientId,
    String? trainerId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignClientToTrainer,
          [],
          {
            #clientId: clientId,
            #trainerId: trainerId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAllPlans() => (super.noSuchMethod(
        Invocation.method(
          #getAllPlans,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAllWorkouts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllWorkouts,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>> getWorkoutStats() => (super.noSuchMethod(
        Invocation.method(
          #getWorkoutStats,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> updateUser({
    required String? userId,
    String? firstName,
    String? lastName,
    String? email,
    String? role,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [],
          {
            #userId: userId,
            #firstName: firstName,
            #lastName: lastName,
            #email: email,
            #role: role,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> deleteUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateUserStatus({
    required String? userId,
    required bool? isActive,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserStatus,
          [],
          {
            #userId: userId,
            #isActive: isActive,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getPlanById(String? planId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlanById,
          [planId],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> createPlan(Map<String, dynamic>? planData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPlan,
          [planData],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> updatePlan(
    String? planId,
    Map<String, dynamic>? planData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePlan,
          [
            planId,
            planData,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> deletePlan(String? planId) => (super.noSuchMethod(
        Invocation.method(
          #deletePlan,
          [planId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> assignPlanToClients(
    String? planId,
    List<String>? clientIds,
    DateTime? startDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignPlanToClients,
          [
            planId,
            clientIds,
            startDate,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> duplicatePlan(String? planId) =>
      (super.noSuchMethod(
        Invocation.method(
          #duplicatePlan,
          [planId],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> cancelPlan(
    String? planId,
    String? clientId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelPlan,
          [
            planId,
            clientId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateWorkoutStatus({
    required String? workoutId,
    bool? isCompleted,
    bool? isMissed,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWorkoutStatus,
          [],
          {
            #workoutId: workoutId,
            #isCompleted: isCompleted,
            #isMissed: isMissed,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteWorkout(String? workoutId) => (super.noSuchMethod(
        Invocation.method(
          #deleteWorkout,
          [workoutId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getClientProfile(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClientProfile,
          [userId],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAIMessages(String? clientId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAIMessages,
          [clientId],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAllAIMessages() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllAIMessages,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> markAIMessageAsRead(String? messageId) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAIMessageAsRead,
          [messageId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> generateAIMessage({
    required String? clientId,
    required String? trigger,
    String? customMessage,
    String? tone,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateAIMessage,
          [],
          {
            #clientId: clientId,
            #trigger: trigger,
            #customMessage: customMessage,
            #tone: tone,
            #metadata: metadata,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<bool> canUnlockNextWeek(String? clientId) => (super.noSuchMethod(
        Invocation.method(
          #canUnlockNextWeek,
          [clientId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>?> requestNextWeek(String? clientId) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestNextWeek,
          [clientId],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getCheckInsByDateRange(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCheckInsByDateRange,
          [
            startDate,
            endDate,
          ],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [WorkoutRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutRepository extends _i1.Mock implements _i5.WorkoutRepository {
  MockWorkoutRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Workout>> getWorkouts() => (super.noSuchMethod(
        Invocation.method(
          #getWorkouts,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Workout>>.value(<_i2.Workout>[]),
      ) as _i4.Future<List<_i2.Workout>>);

  @override
  _i4.Future<_i2.Workout?> getWorkoutById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getWorkoutById,
          [id],
        ),
        returnValue: _i4.Future<_i2.Workout?>.value(),
      ) as _i4.Future<_i2.Workout?>);

  @override
  _i4.Future<_i2.Workout> createWorkout(_i2.Workout? workout) =>
      (super.noSuchMethod(
        Invocation.method(
          #createWorkout,
          [workout],
        ),
        returnValue: _i4.Future<_i2.Workout>.value(_FakeWorkout_0(
          this,
          Invocation.method(
            #createWorkout,
            [workout],
          ),
        )),
      ) as _i4.Future<_i2.Workout>);

  @override
  _i4.Future<_i2.Workout> updateWorkout(_i2.Workout? workout) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWorkout,
          [workout],
        ),
        returnValue: _i4.Future<_i2.Workout>.value(_FakeWorkout_0(
          this,
          Invocation.method(
            #updateWorkout,
            [workout],
          ),
        )),
      ) as _i4.Future<_i2.Workout>);

  @override
  _i4.Future<void> deleteWorkout(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteWorkout,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> logSet(
    String? workoutId,
    String? exerciseId,
    double? weight,
    int? reps,
    double? rpe,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logSet,
          [
            workoutId,
            exerciseId,
            weight,
            reps,
            rpe,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> canUnlockNextWeek(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #canUnlockNextWeek,
          [userId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> requestNextWeek(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #requestNextWeek,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int?> migrateDayOfWeek(_i2.Workout? workout) =>
      (super.noSuchMethod(
        Invocation.method(
          #migrateDayOfWeek,
          [workout],
        ),
        returnValue: _i4.Future<int?>.value(),
      ) as _i4.Future<int?>);

  @override
  _i4.Future<String?> migratePlanId(_i2.Workout? workout) =>
      (super.noSuchMethod(
        Invocation.method(
          #migratePlanId,
          [workout],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);
}
