import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:kinetix_mobile/domain/entities/workout.dart';
import 'package:kinetix_mobile/domain/entities/exercise.dart';
import 'package:uuid/uuid.dart';

/// Helper class for creating test data
class TestHelpers {
  static final _uuid = Uuid();

  /// Create a mock Workout entity for testing
  static Workout createMockWorkout({
    String? id,
    String? serverId,
    String? name,
    String? planId,
    DateTime? scheduledDate,
    int? dayOfWeek,
    bool isCompleted = false,
    bool isMissed = false,
    bool isRestDay = false,
    bool isDirty = false,
    bool isSyncing = false,
    List<Exercise>? exercises,
  }) {
    // Use explicit null check to allow null values when explicitly passed
    // This allows tests to pass null to test migration scenarios
    return Workout(
      id: id ?? _uuid.v4(),
      serverId: serverId,
      name: name ?? 'Test Workout',
      // Only use default if planId is not explicitly provided (not null)
      planId: planId,
      scheduledDate: scheduledDate ?? DateTime.now(),
      // Only use default if dayOfWeek is not explicitly provided (not null)
      dayOfWeek: dayOfWeek,
      isCompleted: isCompleted,
      isMissed: isMissed,
      isRestDay: isRestDay,
      exercises: exercises ?? [],
      isDirty: isDirty,
      isSyncing: isSyncing,
      updatedAt: DateTime.now(),
    );
  }

  /// Create a mock Exercise entity for testing
  static Exercise createMockExercise({
    String? id,
    String? name,
    String? targetMuscle,
    dynamic planReps,
    List<WorkoutSet>? sets,
  }) {
    return Exercise(
      id: id ?? _uuid.v4(),
      name: name ?? 'Test Exercise',
      targetMuscle: targetMuscle ?? 'Chest',
      planReps: planReps ?? '10',
      sets: sets ?? [],
    );
  }

  /// Create a mock WorkoutSet entity for testing
  static WorkoutSet createMockSet({String? id, double? weight, int? reps, double? rpe, bool isCompleted = false}) {
    return WorkoutSet(
      id: id ?? _uuid.v4(),
      weight: weight ?? 0.0,
      reps: reps ?? 0,
      rpe: rpe ?? 0.0,
      isCompleted: isCompleted,
    );
  }

  /// Setup Riverpod container with overrides
  static ProviderContainer setupTestContainer({List<Override> overrides = const []}) {
    return ProviderContainer(overrides: overrides);
  }
}

// Mock classes will be generated by build_runner
// Run: flutter pub run build_runner build
